# Generated by Django 4.2 on 2024-10-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AddField(
            model_name='report',
            name='Name_of_Institutes',
            field=models.CharField(choices=[('others', 'Others'), ('Headq', 'ICMR, Headquarter, New Delhi'), ('nicpr', 'NICPR, Noida, Uttar Pradesh'), ('nimr', 'NIMR, New Delhi')], default='others', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.TextField(blank=True, max_length=240),
        ),
    ]
