# Generated by Django 4.2 on 2024-10-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_report_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='text',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_link',
            field=models.URLField(blank=True),
        ),
    ]
