# Generated by Django 4.2 on 2024-10-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_rename_head_report_head_under_project_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Name_of_Institutes',
            field=models.CharField(choices=[('others', 'Others'), ('Headq', 'ICMR, Headquarter, New Delhi'), ('nicpr', 'NICPR, Noida, Uttar Pradesh'), ('nimr', 'NIMR, New Delhi'), ('niv', 'NIV, Pune'), ('nivmu', 'NIVMU, Mumbai'), ('nirrch', 'NIRRCH, Mumbai'), ('nie', 'NIE, Chennai')], default='others', max_length=10),
        ),
    ]
