# Generated by Django 4.2 on 2024-10-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_report_name_of_institutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='docId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
