# Generated by Django 4.2 on 2024-10-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_report_docid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pdf_link',
            new_name='pdf_link1',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_link2',
            field=models.URLField(blank=True),
        ),
    ]
