# Generated by Django 4.2 on 2024-10-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_rename_pdf_link_report_pdf_link1_report_pdf_link2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='pdf_link1',
            new_name='other_pdf',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='pdf_link2',
            new_name='pdf_link',
        ),
    ]
